package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsCouponUser;
import cn.cqut.lgqs.db.domain.LgqsCouponUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsCouponUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon_user
     *
     * @mbg.generated
     */
    long countByExample(LgqsCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon_user
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon_user
     *
     * @mbg.generated
     */
    int insert(LgqsCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon_user
     *
     * @mbg.generated
     */
    int insertSelective(LgqsCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon_user
     *
     * @mbg.generated
     */
    LgqsCouponUser selectOneByExample(LgqsCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon_user
     *
     * @mbg.generated
     */
    LgqsCouponUser selectOneByExampleSelective(@Param("example") LgqsCouponUserExample example, @Param("selective") LgqsCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon_user
     *
     * @mbg.generated
     */
    List<LgqsCouponUser> selectByExampleSelective(@Param("example") LgqsCouponUserExample example, @Param("selective") LgqsCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon_user
     *
     * @mbg.generated
     */
    List<LgqsCouponUser> selectByExample(LgqsCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon_user
     *
     * @mbg.generated
     */
    LgqsCouponUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon_user
     *
     * @mbg.generated
     */
    LgqsCouponUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon_user
     *
     * @mbg.generated
     */
    LgqsCouponUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsCouponUser record, @Param("example") LgqsCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsCouponUser record, @Param("example") LgqsCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}