package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsGrouponRules;
import cn.cqut.lgqs.db.domain.LgqsGrouponRulesExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsGrouponRulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon_rules
     *
     * @mbg.generated
     */
    long countByExample(LgqsGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon_rules
     *
     * @mbg.generated
     */
    int insert(LgqsGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon_rules
     *
     * @mbg.generated
     */
    int insertSelective(LgqsGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon_rules
     *
     * @mbg.generated
     */
    LgqsGrouponRules selectOneByExample(LgqsGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon_rules
     *
     * @mbg.generated
     */
    LgqsGrouponRules selectOneByExampleSelective(@Param("example") LgqsGrouponRulesExample example, @Param("selective") LgqsGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon_rules
     *
     * @mbg.generated
     */
    List<LgqsGrouponRules> selectByExampleSelective(@Param("example") LgqsGrouponRulesExample example, @Param("selective") LgqsGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon_rules
     *
     * @mbg.generated
     */
    List<LgqsGrouponRules> selectByExample(LgqsGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon_rules
     *
     * @mbg.generated
     */
    LgqsGrouponRules selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon_rules
     *
     * @mbg.generated
     */
    LgqsGrouponRules selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon_rules
     *
     * @mbg.generated
     */
    LgqsGrouponRules selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsGrouponRules record, @Param("example") LgqsGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsGrouponRules record, @Param("example") LgqsGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}