package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsPermission;
import cn.cqut.lgqs.db.domain.LgqsPermissionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_permission
     *
     * @mbg.generated
     */
    long countByExample(LgqsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_permission
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_permission
     *
     * @mbg.generated
     */
    int insert(LgqsPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_permission
     *
     * @mbg.generated
     */
    int insertSelective(LgqsPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_permission
     *
     * @mbg.generated
     */
    LgqsPermission selectOneByExample(LgqsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_permission
     *
     * @mbg.generated
     */
    LgqsPermission selectOneByExampleSelective(@Param("example") LgqsPermissionExample example, @Param("selective") LgqsPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_permission
     *
     * @mbg.generated
     */
    List<LgqsPermission> selectByExampleSelective(@Param("example") LgqsPermissionExample example, @Param("selective") LgqsPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_permission
     *
     * @mbg.generated
     */
    List<LgqsPermission> selectByExample(LgqsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_permission
     *
     * @mbg.generated
     */
    LgqsPermission selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_permission
     *
     * @mbg.generated
     */
    LgqsPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_permission
     *
     * @mbg.generated
     */
    LgqsPermission selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsPermission record, @Param("example") LgqsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsPermission record, @Param("example") LgqsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}