package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsGoodsAttribute;
import cn.cqut.lgqs.db.domain.LgqsGoodsAttributeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsGoodsAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_attribute
     *
     * @mbg.generated
     */
    long countByExample(LgqsGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_attribute
     *
     * @mbg.generated
     */
    int insert(LgqsGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_attribute
     *
     * @mbg.generated
     */
    int insertSelective(LgqsGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_attribute
     *
     * @mbg.generated
     */
    LgqsGoodsAttribute selectOneByExample(LgqsGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_attribute
     *
     * @mbg.generated
     */
    LgqsGoodsAttribute selectOneByExampleSelective(@Param("example") LgqsGoodsAttributeExample example, @Param("selective") LgqsGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_attribute
     *
     * @mbg.generated
     */
    List<LgqsGoodsAttribute> selectByExampleSelective(@Param("example") LgqsGoodsAttributeExample example, @Param("selective") LgqsGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_attribute
     *
     * @mbg.generated
     */
    List<LgqsGoodsAttribute> selectByExample(LgqsGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_attribute
     *
     * @mbg.generated
     */
    LgqsGoodsAttribute selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_attribute
     *
     * @mbg.generated
     */
    LgqsGoodsAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_attribute
     *
     * @mbg.generated
     */
    LgqsGoodsAttribute selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsGoodsAttribute record, @Param("example") LgqsGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsGoodsAttribute record, @Param("example") LgqsGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}