package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsGroupon;
import cn.cqut.lgqs.db.domain.LgqsGrouponExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsGrouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon
     *
     * @mbg.generated
     */
    long countByExample(LgqsGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon
     *
     * @mbg.generated
     */
    int insert(LgqsGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon
     *
     * @mbg.generated
     */
    int insertSelective(LgqsGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon
     *
     * @mbg.generated
     */
    LgqsGroupon selectOneByExample(LgqsGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon
     *
     * @mbg.generated
     */
    LgqsGroupon selectOneByExampleSelective(@Param("example") LgqsGrouponExample example, @Param("selective") LgqsGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon
     *
     * @mbg.generated
     */
    List<LgqsGroupon> selectByExampleSelective(@Param("example") LgqsGrouponExample example, @Param("selective") LgqsGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon
     *
     * @mbg.generated
     */
    List<LgqsGroupon> selectByExample(LgqsGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon
     *
     * @mbg.generated
     */
    LgqsGroupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon
     *
     * @mbg.generated
     */
    LgqsGroupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon
     *
     * @mbg.generated
     */
    LgqsGroupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsGroupon record, @Param("example") LgqsGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsGroupon record, @Param("example") LgqsGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_groupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}