package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsTopic;
import cn.cqut.lgqs.db.domain.LgqsTopicExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_topic
     *
     * @mbg.generated
     */
    long countByExample(LgqsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_topic
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_topic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_topic
     *
     * @mbg.generated
     */
    int insert(LgqsTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_topic
     *
     * @mbg.generated
     */
    int insertSelective(LgqsTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_topic
     *
     * @mbg.generated
     */
    LgqsTopic selectOneByExample(LgqsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_topic
     *
     * @mbg.generated
     */
    LgqsTopic selectOneByExampleSelective(@Param("example") LgqsTopicExample example, @Param("selective") LgqsTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_topic
     *
     * @mbg.generated
     */
    LgqsTopic selectOneByExampleWithBLOBs(LgqsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_topic
     *
     * @mbg.generated
     */
    List<LgqsTopic> selectByExampleSelective(@Param("example") LgqsTopicExample example, @Param("selective") LgqsTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_topic
     *
     * @mbg.generated
     */
    List<LgqsTopic> selectByExampleWithBLOBs(LgqsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_topic
     *
     * @mbg.generated
     */
    List<LgqsTopic> selectByExample(LgqsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_topic
     *
     * @mbg.generated
     */
    LgqsTopic selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_topic
     *
     * @mbg.generated
     */
    LgqsTopic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_topic
     *
     * @mbg.generated
     */
    LgqsTopic selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_topic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsTopic record, @Param("example") LgqsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_topic
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LgqsTopic record, @Param("example") LgqsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_topic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsTopic record, @Param("example") LgqsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LgqsTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}