package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsGoodsSpecification;
import cn.cqut.lgqs.db.domain.LgqsGoodsSpecificationExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsGoodsSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_specification
     *
     * @mbg.generated
     */
    long countByExample(LgqsGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_specification
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_specification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_specification
     *
     * @mbg.generated
     */
    int insert(LgqsGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_specification
     *
     * @mbg.generated
     */
    int insertSelective(LgqsGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_specification
     *
     * @mbg.generated
     */
    LgqsGoodsSpecification selectOneByExample(LgqsGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_specification
     *
     * @mbg.generated
     */
    LgqsGoodsSpecification selectOneByExampleSelective(@Param("example") LgqsGoodsSpecificationExample example, @Param("selective") LgqsGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_specification
     *
     * @mbg.generated
     */
    List<LgqsGoodsSpecification> selectByExampleSelective(@Param("example") LgqsGoodsSpecificationExample example, @Param("selective") LgqsGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_specification
     *
     * @mbg.generated
     */
    List<LgqsGoodsSpecification> selectByExample(LgqsGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_specification
     *
     * @mbg.generated
     */
    LgqsGoodsSpecification selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_specification
     *
     * @mbg.generated
     */
    LgqsGoodsSpecification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_specification
     *
     * @mbg.generated
     */
    LgqsGoodsSpecification selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_specification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsGoodsSpecification record, @Param("example") LgqsGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_specification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsGoodsSpecification record, @Param("example") LgqsGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}