package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsNotice;
import cn.cqut.lgqs.db.domain.LgqsNoticeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice
     *
     * @mbg.generated
     */
    long countByExample(LgqsNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice
     *
     * @mbg.generated
     */
    int insert(LgqsNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice
     *
     * @mbg.generated
     */
    int insertSelective(LgqsNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice
     *
     * @mbg.generated
     */
    LgqsNotice selectOneByExample(LgqsNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice
     *
     * @mbg.generated
     */
    LgqsNotice selectOneByExampleSelective(@Param("example") LgqsNoticeExample example, @Param("selective") LgqsNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice
     *
     * @mbg.generated
     */
    List<LgqsNotice> selectByExampleSelective(@Param("example") LgqsNoticeExample example, @Param("selective") LgqsNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice
     *
     * @mbg.generated
     */
    List<LgqsNotice> selectByExample(LgqsNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice
     *
     * @mbg.generated
     */
    LgqsNotice selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice
     *
     * @mbg.generated
     */
    LgqsNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice
     *
     * @mbg.generated
     */
    LgqsNotice selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsNotice record, @Param("example") LgqsNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsNotice record, @Param("example") LgqsNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}