package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsNoticeAdmin;
import cn.cqut.lgqs.db.domain.LgqsNoticeAdminExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsNoticeAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice_admin
     *
     * @mbg.generated
     */
    long countByExample(LgqsNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice_admin
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice_admin
     *
     * @mbg.generated
     */
    int insert(LgqsNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice_admin
     *
     * @mbg.generated
     */
    int insertSelective(LgqsNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice_admin
     *
     * @mbg.generated
     */
    LgqsNoticeAdmin selectOneByExample(LgqsNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice_admin
     *
     * @mbg.generated
     */
    LgqsNoticeAdmin selectOneByExampleSelective(@Param("example") LgqsNoticeAdminExample example, @Param("selective") LgqsNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice_admin
     *
     * @mbg.generated
     */
    List<LgqsNoticeAdmin> selectByExampleSelective(@Param("example") LgqsNoticeAdminExample example, @Param("selective") LgqsNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice_admin
     *
     * @mbg.generated
     */
    List<LgqsNoticeAdmin> selectByExample(LgqsNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice_admin
     *
     * @mbg.generated
     */
    LgqsNoticeAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice_admin
     *
     * @mbg.generated
     */
    LgqsNoticeAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice_admin
     *
     * @mbg.generated
     */
    LgqsNoticeAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsNoticeAdmin record, @Param("example") LgqsNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsNoticeAdmin record, @Param("example") LgqsNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_notice_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}