package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsStorage;
import cn.cqut.lgqs.db.domain.LgqsStorageExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_storage
     *
     * @mbg.generated
     */
    long countByExample(LgqsStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_storage
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_storage
     *
     * @mbg.generated
     */
    int insert(LgqsStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_storage
     *
     * @mbg.generated
     */
    int insertSelective(LgqsStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_storage
     *
     * @mbg.generated
     */
    LgqsStorage selectOneByExample(LgqsStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_storage
     *
     * @mbg.generated
     */
    LgqsStorage selectOneByExampleSelective(@Param("example") LgqsStorageExample example, @Param("selective") LgqsStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_storage
     *
     * @mbg.generated
     */
    List<LgqsStorage> selectByExampleSelective(@Param("example") LgqsStorageExample example, @Param("selective") LgqsStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_storage
     *
     * @mbg.generated
     */
    List<LgqsStorage> selectByExample(LgqsStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_storage
     *
     * @mbg.generated
     */
    LgqsStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_storage
     *
     * @mbg.generated
     */
    LgqsStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_storage
     *
     * @mbg.generated
     */
    LgqsStorage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_storage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsStorage record, @Param("example") LgqsStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_storage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsStorage record, @Param("example") LgqsStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}