package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsCart;
import cn.cqut.lgqs.db.domain.LgqsCartExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_cart
     *
     * @mbg.generated
     */
    long countByExample(LgqsCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_cart
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_cart
     *
     * @mbg.generated
     */
    int insert(LgqsCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_cart
     *
     * @mbg.generated
     */
    int insertSelective(LgqsCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_cart
     *
     * @mbg.generated
     */
    LgqsCart selectOneByExample(LgqsCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_cart
     *
     * @mbg.generated
     */
    LgqsCart selectOneByExampleSelective(@Param("example") LgqsCartExample example, @Param("selective") LgqsCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_cart
     *
     * @mbg.generated
     */
    List<LgqsCart> selectByExampleSelective(@Param("example") LgqsCartExample example, @Param("selective") LgqsCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_cart
     *
     * @mbg.generated
     */
    List<LgqsCart> selectByExample(LgqsCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_cart
     *
     * @mbg.generated
     */
    LgqsCart selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_cart
     *
     * @mbg.generated
     */
    LgqsCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_cart
     *
     * @mbg.generated
     */
    LgqsCart selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_cart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsCart record, @Param("example") LgqsCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_cart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsCart record, @Param("example") LgqsCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}