package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsOrder;
import cn.cqut.lgqs.db.domain.LgqsOrderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_order
     *
     * @mbg.generated
     */
    long countByExample(LgqsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_order
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_order
     *
     * @mbg.generated
     */
    int insert(LgqsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_order
     *
     * @mbg.generated
     */
    int insertSelective(LgqsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_order
     *
     * @mbg.generated
     */
    LgqsOrder selectOneByExample(LgqsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_order
     *
     * @mbg.generated
     */
    LgqsOrder selectOneByExampleSelective(@Param("example") LgqsOrderExample example, @Param("selective") LgqsOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_order
     *
     * @mbg.generated
     */
    List<LgqsOrder> selectByExampleSelective(@Param("example") LgqsOrderExample example, @Param("selective") LgqsOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_order
     *
     * @mbg.generated
     */
    List<LgqsOrder> selectByExample(LgqsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_order
     *
     * @mbg.generated
     */
    LgqsOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_order
     *
     * @mbg.generated
     */
    LgqsOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_order
     *
     * @mbg.generated
     */
    LgqsOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsOrder record, @Param("example") LgqsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsOrder record, @Param("example") LgqsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_order
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_order
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}