package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsFootprint;
import cn.cqut.lgqs.db.domain.LgqsFootprintExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsFootprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_footprint
     *
     * @mbg.generated
     */
    long countByExample(LgqsFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_footprint
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_footprint
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_footprint
     *
     * @mbg.generated
     */
    int insert(LgqsFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_footprint
     *
     * @mbg.generated
     */
    int insertSelective(LgqsFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_footprint
     *
     * @mbg.generated
     */
    LgqsFootprint selectOneByExample(LgqsFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_footprint
     *
     * @mbg.generated
     */
    LgqsFootprint selectOneByExampleSelective(@Param("example") LgqsFootprintExample example, @Param("selective") LgqsFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_footprint
     *
     * @mbg.generated
     */
    List<LgqsFootprint> selectByExampleSelective(@Param("example") LgqsFootprintExample example, @Param("selective") LgqsFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_footprint
     *
     * @mbg.generated
     */
    List<LgqsFootprint> selectByExample(LgqsFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_footprint
     *
     * @mbg.generated
     */
    LgqsFootprint selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_footprint
     *
     * @mbg.generated
     */
    LgqsFootprint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_footprint
     *
     * @mbg.generated
     */
    LgqsFootprint selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_footprint
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsFootprint record, @Param("example") LgqsFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_footprint
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsFootprint record, @Param("example") LgqsFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_footprint
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_footprint
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}