package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsCategory;
import cn.cqut.lgqs.db.domain.LgqsCategoryExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_category
     *
     * @mbg.generated
     */
    long countByExample(LgqsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_category
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_category
     *
     * @mbg.generated
     */
    int insert(LgqsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_category
     *
     * @mbg.generated
     */
    int insertSelective(LgqsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_category
     *
     * @mbg.generated
     */
    LgqsCategory selectOneByExample(LgqsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_category
     *
     * @mbg.generated
     */
    LgqsCategory selectOneByExampleSelective(@Param("example") LgqsCategoryExample example, @Param("selective") LgqsCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_category
     *
     * @mbg.generated
     */
    List<LgqsCategory> selectByExampleSelective(@Param("example") LgqsCategoryExample example, @Param("selective") LgqsCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_category
     *
     * @mbg.generated
     */
    List<LgqsCategory> selectByExample(LgqsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_category
     *
     * @mbg.generated
     */
    LgqsCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_category
     *
     * @mbg.generated
     */
    LgqsCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_category
     *
     * @mbg.generated
     */
    LgqsCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsCategory record, @Param("example") LgqsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsCategory record, @Param("example") LgqsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_category
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_category
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}