package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsRole;
import cn.cqut.lgqs.db.domain.LgqsRoleExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_role
     *
     * @mbg.generated
     */
    long countByExample(LgqsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_role
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_role
     *
     * @mbg.generated
     */
    int insert(LgqsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_role
     *
     * @mbg.generated
     */
    int insertSelective(LgqsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_role
     *
     * @mbg.generated
     */
    LgqsRole selectOneByExample(LgqsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_role
     *
     * @mbg.generated
     */
    LgqsRole selectOneByExampleSelective(@Param("example") LgqsRoleExample example, @Param("selective") LgqsRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_role
     *
     * @mbg.generated
     */
    List<LgqsRole> selectByExampleSelective(@Param("example") LgqsRoleExample example, @Param("selective") LgqsRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_role
     *
     * @mbg.generated
     */
    List<LgqsRole> selectByExample(LgqsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_role
     *
     * @mbg.generated
     */
    LgqsRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_role
     *
     * @mbg.generated
     */
    LgqsRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_role
     *
     * @mbg.generated
     */
    LgqsRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsRole record, @Param("example") LgqsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsRole record, @Param("example") LgqsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}