package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsGoods;
import cn.cqut.lgqs.db.domain.LgqsGoodsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods
     *
     * @mbg.generated
     */
    long countByExample(LgqsGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods
     *
     * @mbg.generated
     */
    int insert(LgqsGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods
     *
     * @mbg.generated
     */
    int insertSelective(LgqsGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods
     *
     * @mbg.generated
     */
    LgqsGoods selectOneByExample(LgqsGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods
     *
     * @mbg.generated
     */
    LgqsGoods selectOneByExampleSelective(@Param("example") LgqsGoodsExample example, @Param("selective") LgqsGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods
     *
     * @mbg.generated
     */
    LgqsGoods selectOneByExampleWithBLOBs(LgqsGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods
     *
     * @mbg.generated
     */
    List<LgqsGoods> selectByExampleSelective(@Param("example") LgqsGoodsExample example, @Param("selective") LgqsGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods
     *
     * @mbg.generated
     */
    List<LgqsGoods> selectByExampleWithBLOBs(LgqsGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods
     *
     * @mbg.generated
     */
    List<LgqsGoods> selectByExample(LgqsGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods
     *
     * @mbg.generated
     */
    LgqsGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods
     *
     * @mbg.generated
     */
    LgqsGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods
     *
     * @mbg.generated
     */
    LgqsGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsGoods record, @Param("example") LgqsGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LgqsGoods record, @Param("example") LgqsGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsGoods record, @Param("example") LgqsGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LgqsGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}