package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsCoupon;
import cn.cqut.lgqs.db.domain.LgqsCouponExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon
     *
     * @mbg.generated
     */
    long countByExample(LgqsCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon
     *
     * @mbg.generated
     */
    int insert(LgqsCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon
     *
     * @mbg.generated
     */
    int insertSelective(LgqsCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon
     *
     * @mbg.generated
     */
    LgqsCoupon selectOneByExample(LgqsCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon
     *
     * @mbg.generated
     */
    LgqsCoupon selectOneByExampleSelective(@Param("example") LgqsCouponExample example, @Param("selective") LgqsCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon
     *
     * @mbg.generated
     */
    List<LgqsCoupon> selectByExampleSelective(@Param("example") LgqsCouponExample example, @Param("selective") LgqsCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon
     *
     * @mbg.generated
     */
    List<LgqsCoupon> selectByExample(LgqsCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon
     *
     * @mbg.generated
     */
    LgqsCoupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon
     *
     * @mbg.generated
     */
    LgqsCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon
     *
     * @mbg.generated
     */
    LgqsCoupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsCoupon record, @Param("example") LgqsCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsCoupon record, @Param("example") LgqsCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}