package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsAddress;
import cn.cqut.lgqs.db.domain.LgqsAddressExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_address
     *
     * @mbg.generated
     */
    long countByExample(LgqsAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_address
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_address
     *
     * @mbg.generated
     */
    int insert(LgqsAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_address
     *
     * @mbg.generated
     */
    int insertSelective(LgqsAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_address
     *
     * @mbg.generated
     */
    LgqsAddress selectOneByExample(LgqsAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_address
     *
     * @mbg.generated
     */
    LgqsAddress selectOneByExampleSelective(@Param("example") LgqsAddressExample example, @Param("selective") LgqsAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_address
     *
     * @mbg.generated
     */
    List<LgqsAddress> selectByExampleSelective(@Param("example") LgqsAddressExample example, @Param("selective") LgqsAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_address
     *
     * @mbg.generated
     */
    List<LgqsAddress> selectByExample(LgqsAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_address
     *
     * @mbg.generated
     */
    LgqsAddress selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_address
     *
     * @mbg.generated
     */
    LgqsAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_address
     *
     * @mbg.generated
     */
    LgqsAddress selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_address
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsAddress record, @Param("example") LgqsAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_address
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsAddress record, @Param("example") LgqsAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_address
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_address
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}