package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsSystem;
import cn.cqut.lgqs.db.domain.LgqsSystemExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_system
     *
     * @mbg.generated
     */
    long countByExample(LgqsSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_system
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_system
     *
     * @mbg.generated
     */
    int insert(LgqsSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_system
     *
     * @mbg.generated
     */
    int insertSelective(LgqsSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_system
     *
     * @mbg.generated
     */
    LgqsSystem selectOneByExample(LgqsSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_system
     *
     * @mbg.generated
     */
    LgqsSystem selectOneByExampleSelective(@Param("example") LgqsSystemExample example, @Param("selective") LgqsSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_system
     *
     * @mbg.generated
     */
    List<LgqsSystem> selectByExampleSelective(@Param("example") LgqsSystemExample example, @Param("selective") LgqsSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_system
     *
     * @mbg.generated
     */
    List<LgqsSystem> selectByExample(LgqsSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_system
     *
     * @mbg.generated
     */
    LgqsSystem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_system
     *
     * @mbg.generated
     */
    LgqsSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_system
     *
     * @mbg.generated
     */
    LgqsSystem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsSystem record, @Param("example") LgqsSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsSystem record, @Param("example") LgqsSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_system
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_system
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}