package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsIssue;
import cn.cqut.lgqs.db.domain.LgqsIssueExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsIssueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_issue
     *
     * @mbg.generated
     */
    long countByExample(LgqsIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_issue
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_issue
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_issue
     *
     * @mbg.generated
     */
    int insert(LgqsIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_issue
     *
     * @mbg.generated
     */
    int insertSelective(LgqsIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_issue
     *
     * @mbg.generated
     */
    LgqsIssue selectOneByExample(LgqsIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_issue
     *
     * @mbg.generated
     */
    LgqsIssue selectOneByExampleSelective(@Param("example") LgqsIssueExample example, @Param("selective") LgqsIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_issue
     *
     * @mbg.generated
     */
    List<LgqsIssue> selectByExampleSelective(@Param("example") LgqsIssueExample example, @Param("selective") LgqsIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_issue
     *
     * @mbg.generated
     */
    List<LgqsIssue> selectByExample(LgqsIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_issue
     *
     * @mbg.generated
     */
    LgqsIssue selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_issue
     *
     * @mbg.generated
     */
    LgqsIssue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_issue
     *
     * @mbg.generated
     */
    LgqsIssue selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_issue
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsIssue record, @Param("example") LgqsIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_issue
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsIssue record, @Param("example") LgqsIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_issue
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_issue
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}