package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsComment;
import cn.cqut.lgqs.db.domain.LgqsCommentExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_comment
     *
     * @mbg.generated
     */
    long countByExample(LgqsCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_comment
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_comment
     *
     * @mbg.generated
     */
    int insert(LgqsComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_comment
     *
     * @mbg.generated
     */
    int insertSelective(LgqsComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_comment
     *
     * @mbg.generated
     */
    LgqsComment selectOneByExample(LgqsCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_comment
     *
     * @mbg.generated
     */
    LgqsComment selectOneByExampleSelective(@Param("example") LgqsCommentExample example, @Param("selective") LgqsComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_comment
     *
     * @mbg.generated
     */
    List<LgqsComment> selectByExampleSelective(@Param("example") LgqsCommentExample example, @Param("selective") LgqsComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_comment
     *
     * @mbg.generated
     */
    List<LgqsComment> selectByExample(LgqsCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_comment
     *
     * @mbg.generated
     */
    LgqsComment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_comment
     *
     * @mbg.generated
     */
    LgqsComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_comment
     *
     * @mbg.generated
     */
    LgqsComment selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsComment record, @Param("example") LgqsCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsComment record, @Param("example") LgqsCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}