package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsFeedback;
import cn.cqut.lgqs.db.domain.LgqsFeedbackExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_feedback
     *
     * @mbg.generated
     */
    long countByExample(LgqsFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_feedback
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_feedback
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_feedback
     *
     * @mbg.generated
     */
    int insert(LgqsFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_feedback
     *
     * @mbg.generated
     */
    int insertSelective(LgqsFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_feedback
     *
     * @mbg.generated
     */
    LgqsFeedback selectOneByExample(LgqsFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_feedback
     *
     * @mbg.generated
     */
    LgqsFeedback selectOneByExampleSelective(@Param("example") LgqsFeedbackExample example, @Param("selective") LgqsFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_feedback
     *
     * @mbg.generated
     */
    List<LgqsFeedback> selectByExampleSelective(@Param("example") LgqsFeedbackExample example, @Param("selective") LgqsFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_feedback
     *
     * @mbg.generated
     */
    List<LgqsFeedback> selectByExample(LgqsFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_feedback
     *
     * @mbg.generated
     */
    LgqsFeedback selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_feedback
     *
     * @mbg.generated
     */
    LgqsFeedback selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_feedback
     *
     * @mbg.generated
     */
    LgqsFeedback selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_feedback
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsFeedback record, @Param("example") LgqsFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_feedback
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsFeedback record, @Param("example") LgqsFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_feedback
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_feedback
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}