package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsKeyword;
import cn.cqut.lgqs.db.domain.LgqsKeywordExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_keyword
     *
     * @mbg.generated
     */
    long countByExample(LgqsKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_keyword
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_keyword
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_keyword
     *
     * @mbg.generated
     */
    int insert(LgqsKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_keyword
     *
     * @mbg.generated
     */
    int insertSelective(LgqsKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_keyword
     *
     * @mbg.generated
     */
    LgqsKeyword selectOneByExample(LgqsKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_keyword
     *
     * @mbg.generated
     */
    LgqsKeyword selectOneByExampleSelective(@Param("example") LgqsKeywordExample example, @Param("selective") LgqsKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_keyword
     *
     * @mbg.generated
     */
    List<LgqsKeyword> selectByExampleSelective(@Param("example") LgqsKeywordExample example, @Param("selective") LgqsKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_keyword
     *
     * @mbg.generated
     */
    List<LgqsKeyword> selectByExample(LgqsKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_keyword
     *
     * @mbg.generated
     */
    LgqsKeyword selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_keyword
     *
     * @mbg.generated
     */
    LgqsKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_keyword
     *
     * @mbg.generated
     */
    LgqsKeyword selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_keyword
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsKeyword record, @Param("example") LgqsKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_keyword
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsKeyword record, @Param("example") LgqsKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}