package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsCollect;
import cn.cqut.lgqs.db.domain.LgqsCollectExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_collect
     *
     * @mbg.generated
     */
    long countByExample(LgqsCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_collect
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_collect
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_collect
     *
     * @mbg.generated
     */
    int insert(LgqsCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_collect
     *
     * @mbg.generated
     */
    int insertSelective(LgqsCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_collect
     *
     * @mbg.generated
     */
    LgqsCollect selectOneByExample(LgqsCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_collect
     *
     * @mbg.generated
     */
    LgqsCollect selectOneByExampleSelective(@Param("example") LgqsCollectExample example, @Param("selective") LgqsCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_collect
     *
     * @mbg.generated
     */
    List<LgqsCollect> selectByExampleSelective(@Param("example") LgqsCollectExample example, @Param("selective") LgqsCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_collect
     *
     * @mbg.generated
     */
    List<LgqsCollect> selectByExample(LgqsCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_collect
     *
     * @mbg.generated
     */
    LgqsCollect selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_collect
     *
     * @mbg.generated
     */
    LgqsCollect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_collect
     *
     * @mbg.generated
     */
    LgqsCollect selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_collect
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsCollect record, @Param("example") LgqsCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_collect
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsCollect record, @Param("example") LgqsCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}