package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsBrand;
import cn.cqut.lgqs.db.domain.LgqsBrandExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_brand
     *
     * @mbg.generated
     */
    long countByExample(LgqsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_brand
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_brand
     *
     * @mbg.generated
     */
    int insert(LgqsBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_brand
     *
     * @mbg.generated
     */
    int insertSelective(LgqsBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_brand
     *
     * @mbg.generated
     */
    LgqsBrand selectOneByExample(LgqsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_brand
     *
     * @mbg.generated
     */
    LgqsBrand selectOneByExampleSelective(@Param("example") LgqsBrandExample example, @Param("selective") LgqsBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_brand
     *
     * @mbg.generated
     */
    List<LgqsBrand> selectByExampleSelective(@Param("example") LgqsBrandExample example, @Param("selective") LgqsBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_brand
     *
     * @mbg.generated
     */
    List<LgqsBrand> selectByExample(LgqsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_brand
     *
     * @mbg.generated
     */
    LgqsBrand selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_brand
     *
     * @mbg.generated
     */
    LgqsBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_brand
     *
     * @mbg.generated
     */
    LgqsBrand selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsBrand record, @Param("example") LgqsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsBrand record, @Param("example") LgqsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}