package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsLog;
import cn.cqut.lgqs.db.domain.LgqsLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_log
     *
     * @mbg.generated
     */
    long countByExample(LgqsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_log
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_log
     *
     * @mbg.generated
     */
    int insert(LgqsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_log
     *
     * @mbg.generated
     */
    int insertSelective(LgqsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_log
     *
     * @mbg.generated
     */
    LgqsLog selectOneByExample(LgqsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_log
     *
     * @mbg.generated
     */
    LgqsLog selectOneByExampleSelective(@Param("example") LgqsLogExample example, @Param("selective") LgqsLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_log
     *
     * @mbg.generated
     */
    List<LgqsLog> selectByExampleSelective(@Param("example") LgqsLogExample example, @Param("selective") LgqsLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_log
     *
     * @mbg.generated
     */
    List<LgqsLog> selectByExample(LgqsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_log
     *
     * @mbg.generated
     */
    LgqsLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_log
     *
     * @mbg.generated
     */
    LgqsLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_log
     *
     * @mbg.generated
     */
    LgqsLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsLog record, @Param("example") LgqsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsLog record, @Param("example") LgqsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_log
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_log
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}