package cn.cqut.lgqs.db.dao;

import cn.cqut.lgqs.db.domain.LgqsUser;
import cn.cqut.lgqs.db.domain.LgqsUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LgqsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_user
     *
     * @mbg.generated
     */
    long countByExample(LgqsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_user
     *
     * @mbg.generated
     */
    int deleteByExample(LgqsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_user
     *
     * @mbg.generated
     */
    int insert(LgqsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_user
     *
     * @mbg.generated
     */
    int insertSelective(LgqsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_user
     *
     * @mbg.generated
     */
    LgqsUser selectOneByExample(LgqsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_user
     *
     * @mbg.generated
     */
    LgqsUser selectOneByExampleSelective(@Param("example") LgqsUserExample example, @Param("selective") LgqsUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_user
     *
     * @mbg.generated
     */
    List<LgqsUser> selectByExampleSelective(@Param("example") LgqsUserExample example, @Param("selective") LgqsUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_user
     *
     * @mbg.generated
     */
    List<LgqsUser> selectByExample(LgqsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_user
     *
     * @mbg.generated
     */
    LgqsUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LgqsUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_user
     *
     * @mbg.generated
     */
    LgqsUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_user
     *
     * @mbg.generated
     */
    LgqsUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LgqsUser record, @Param("example") LgqsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LgqsUser record, @Param("example") LgqsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LgqsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LgqsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LgqsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lgqs_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}